### PR TITLE
Change "Handlebars" to "handlebars" in task file to fix bug that causes Handlebars object to be undefined

### PR DESCRIPTION
**Pull request by aevange**
This is necessary because passing in a capital "H" in the compiled files will cause an error such that the Handlebars object in the body of the code is undefined.

The following is the error I was getting in the console.
image

I made the change from:
image

to:
image

and no longer received an error and my page loaded properly.
image

### CODE REVIEW

**Comment by mrDarcyMurphy** [comment]
Interesting. i haven't seen that issue before. Do you have an example of how to reproduce the issue?

**Comment by aevange** [comment]
I'm not sure everything you would need (I would just point you to the repo we're working on, but it's private).

This error was happening on all 4 machines we were using (Dell loptop, Macbook pro, Macbook air and Macmini)

Below are sections of our package.json, bower.json (along with the listing of versions) and Gruntfile.js that you would need.

Let me know if there is anything else to make this more clear, and thanks!

package.json:

```
"devDependencies": {
  "grunt": "~0.4.1",
  "grunt-nodemon": "0.0.9",
  "grunt-contrib-requirejs": "~0.4.0",
  "grunt-contrib-jshint": "~0.3.0",
  "grunt-shell": "~0.3.1",
  "grunt-mocha-test": "~0.6.2",
  "mongoose": "~3.6.19",
  "superagent": "~0.15.4",
  "expect.js": "~0.2.0",
  "uglify-js": "~2.2.5",
  "passport": "~0.1.17",
  "util": "~0.4.9",
  "crypto": "0.0.3",
  "passport-reddit": "~0.2.3",
  "grunt-node-inspector": "~0.1.0",
  "grunt-contrib-stylus": "~0.8.0",
  "grunt-contrib-watch": "~0.5.3",
  "grunt-concurrent": "~0.4.0",
  "fluidity": "~0.2.0",
  "stylus": "~0.38.0",
  "handlebars": "~1.0.12",
  "grunt-handlebars-requirejs": "~0.1.0"
},
```

bower.json:

```
"dependencies": {
  "backbone": "latest",
  "lodash": "latest",
  "jquery": "latest",
  "requirejs": "latest",
  "text": "latest",
  "bootstrap": "latest",
  "font-awesome": "latest",
  "handlebars": "latest"
}
```

image

Gruntfile:

```
  handlebars_requirejs: {
    basic: {
      files: {
        // folder : files
        // files will be converted into modules and dumped into the folder
        'public/js/app/templates/': 'public/template/*.hbs'
      }
    }
  }

});

grunt.loadNpmTasks('grunt-handlebars-requirejs');
```

**Comment by mrDarcyMurphy** [comment]
Thanks.

What seems odd to me is that it would matter in the first place. Requirejs should set Handlebars to whatever variable name you give it in the module definition, whether upper or lowercase. That said, handlebars does some weird stuff at times.

There's also two types of handlebars, the runtime and the full on library. That might be where the problem is coming from. Maybe.

**Comment by aevange** [comment]
Yeah, that's what was so puzzling at first.

As you said, it could totally be the problem that handlebars has a mind of its own almost.

My best guess is there must be a namespace collision because if I name the argument in the task file to "handle" or "h" or "HANDLEBARS" it works just fine. But as soon as it's named "Handlebars" I get this in the console:

image

**Comment by mrDarcyMurphy** [comment]
I'm going to close this for now because I know some people who are using this in production without issue and changing this would cause problems for them. Also, it seems more likely that there's a conflict somewhere in your code rather than an issue with this.

**Pull request closed without merging**
